# Generated by Django 2.2.6 on 2019-10-04 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('uuid', models.UUIDField(help_text='UUID of the device (as displayed)', primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('uuid', models.UUIDField(help_text='UIUD of the recording', primary_key=True, serialize=False)),
                ('date', models.DateTimeField(help_text='Date the conversation took place')),
                ('date_uploaded', models.DateTimeField(auto_now_add=True, help_text='Date the conversation was uploaded')),
                ('gammatone', models.ImageField(default='blank.png', help_text='Media path of the saved gammatone', upload_to='gammatones/')),
                ('device', models.ForeignKey(help_text='Device that recorded the conversation', on_delete=django.db.models.deletion.PROTECT, to='db.Device')),
            ],
            options={
                'unique_together': {('device', 'date')},
            },
        ),
    ]
