# Generated by Django 2.2.6 on 2019-10-04 16:08

import db.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='gammatone',
            field=models.ImageField(help_text='Media path of the saved gammatone', unique=True, upload_to=db.utils.path_and_rename),
        ),
    ]
